export const SET_USER = 'SET_USER';
export const SET_USER_TYPE = 'SET_USER_TYPE';
export const SET_USER_CHILD = 'SET_USER_CHILD';
export const SET_USER_REGISTERED_TRUE = 'SET_USER_REGISTERED_TRUE';
export const SET_SIGNIN_USER = 'SET_SIGNIN_USER';
export const SET_WHICH_USER_MODE = 'SET_WHICH_USER_MODE';
export const SIGNIN_OUT = 'SIGNIN_OUT';

export const REMOVE_USER = 'REMOVE_USER';
export const ADD_CHILD = 'ADD_CHILD';
export const SET_CHORELIST = 'SET_CHORELIST';
export const ADD_TO_CHORELIST = 'ADD_TO_CHORELIST';


