export const SET_USER = 'SET_USER';
export const SET_USER_TYPE = 'SET_USER_TYPE';
export const SET_USER_ID = 'SET_USER_ID';
export const SET_USER_CHILD = 'SET_USER_CHILD';
export const SET_USER_REGISTERED_TRUE = 'SET_USER_REGISTERED_TRUE';
export const SET_SIGNIN_USER = 'SET_SIGNIN_USER';
export const SET_WHICH_USER_MODE = 'SET_WHICH_USER_MODE';
export const SIGNIN_OUT = 'SIGNIN_OUT';

export const SET_EDIT_CHILD = 'SET_EDIT_CHILD';
export const SET_UPDATE_CHILD = 'SET_UPDATE_CHILD';
export const SET_DELETE_CHILD = 'SET_DELETE_CHILD';
export const SET_EDIT_MODE = 'SET_EDIT_MODE';

//chore
export const ADD_TO_CHORELIST = 'ADD_TO_CHORELIST';
export const SET_EDIT_CHORE = 'SET_EDIT_CHORE';
export const EDIT_THE_CHORELIST = 'EDIT_THE_CHORELIST';
export const SET_DELETE_CHORE = 'SET_DELETE_CHORE';

// schedule
export const SET_SCHEDULES = 'SET_SCHEDULES';
export const SET_SELECTED_SCHEDULE = 'SET_SELECTED_SCHEDULE';


